### ISSUE TITLE
去掉视频上下的黑边？

### ISSUE THREAD

**Issue by Zeaa** [chenmingbiao/BCVideoFilter#1]
看到BCGLKView中的-drawRect:方法中有构造解码比例，这里设置一个什么参数可以去掉视频上下的黑边呢，大神~

**Comment by Zeaa** [comment]
我是在BCGLKView中这样写
```
- (void) drawRect:(CGRect)rect {
    
    CGRect origninalRect = CGRectMake(0, 0, self.drawableWidth, self.drawableHeight);
    [coreImageContext drawImage:self.image inRect:origninalRect fromRect:self.image.extent];
}
```

**Comment by chenmingbiao** [comment]
是的，目前那块我写死的，直接修改origninalRect即可
不过这个框架用CADisplayLink的方式不是很好，会有5%-10%的丢帧，可以考虑一下优化，可提PR :)

**Comment by Zeaa** [comment]
为啥丢帧。。？后来发现这个其实用AVVideoComposition也同样可以处理滤镜的显示,AVPlayerItem有个videoComposition属性，同样可以实时预览滤镜的
`playerItem.videoComposition = [AVVideoComposition videoCompositionWithAsset:self.composition applyingCIFiltersWithHandler:^(AVAsynchronousCIImageFilteringRequest * _Nonnull request) {`
而且重点是需要保存到本地时也还是需要AVVideoComposition这个类，所以现在准备直接用AVPlayer去显示，不过还有个不明白的问题是这两种显示有什么区别，什么时候用啥哈。。。。。。。。。。。。。。。。。。。。。。。。。。。
